### ISSUE TITLE
Supported JPEG decoder ?

### ISSUE THREAD

**Issue by klugem** [CESNET/GPUJPEG#11]
Does GPUJPEG create a "normal" JPEG that can be read by any JPEG decoder ?

**Comment by MartinPulec** [comment]
Hi Michael,

yes, GPUJPEG is creating ordinary JPEG (JFIF) images. Only unusual thing is that it is recommended to enable restart markers for better encoding paralelization which is part of the standard but some decoders don't implement (or didn't use to). But this is only optional. On the other hand, the GPUJPEG decoder is unfortunately able to decode only subset of JPEG images (namely it doesn't support Exif).

Martin

**Comment by klugem** [comment]
Hi Martin,

thanks for the fast reply. :)

I already played around a little bit but so far I was not able get anything that was not a "broken" picture. But now I know that it is worth to get this running. ;)

Michael

**Comment by MartinPulec** [comment]
Hi Michael,
no problem. Let us know if you discover some problem or there is something unclear. The library (as well as the sample application) is indeed supposed to work so if you hit a bug, I'll be glad if you let us know :)

Martin

**Comment by klugem** [comment]
Hi Martin,

I was able to decode and encode an image using the functions your library provides. It is way faster than libjpeg or libjpeg-turbo on the CPU. :)

Now I'm trying to encode a image which was modified with openCV and is stored in GpuMat / Mat class.
I tried to use the 'data' field of openCV's Mat class but this did not worked.

Can you give me a hint how this might work ?

Michael

PS: I found a thread were someone used the decoder to feed openCV. I want to do the opposite...
https://github.com/hoopoe/gpujpeg/issues/1

**Comment by klugem** [comment]
Got it working:

`uint8_t* image = img_dst.data;`
`gpujpeg_encoder_input_set_image(&encoder_input, image);`

:)
