### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by andviane** [CESNET/GPUJPEG#12]
When building recent master branch from the source under Linux, I was able to convert the small 16x16 image from .jpg into rgb but cannot convert the produced image (created by gpujpeg itself) from rgb back into jpg. The error messages are:

```
audrius@leo:~/catkin_ws/src/gpujpeg/GPUJPEG$ ./gpujpeg  sv.rgb sv.jpg -e
CUDA driver version:   9.1
CUDA runtime version:  9.0
Using Device #0:       GeForce GTX 1080 Ti (c.c. 6.1)

Encoding Image [sv.rgb]
Load Image:                0.43 ms
Floating point exception (core dumped)
```
gdb provides the following information

```
[New LWP 29663]
[New LWP 29678]
[New LWP 29677]
[New LWP 29679]
Core was generated by `/home/audrius/catkin_ws/src/gpujpeg/GPUJPEG/.libs/lt-gpujpeg sv.rgb sv.jpg -e'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007f19896d1dbb in ?? ()
[Current thread is 1 (LWP 29663)]
```

**Comment by andviane** [comment]
Just discovered that the crash does not happen if -s option is given with image dimensions.

**Comment by MartinPulec** [comment]
Hi Audrius,

thanks for reporting - the crash should not happen. However the size is rather mandatory (for encode), because otherwise the encoder cannot determine the image dimensions (the file is without headers). I've added a few checks to the code.

Regards,
Martin
