### ISSUE TITLE
Encoded Image Not Displaying Correctly on MacOs

### ISSUE THREAD

**Issue by mkehoe-ovio** [CESNET/GPUJPEG#16]
Hello,

I have been using this library for a while now and everything seems to be working correctly, except for one use case. Images encoded with GpuJpeg do not seem to be displaying correctly on MacOs in the Apple "Preview" application. The images are encoded on the windows platform and then copied to the mac. We have tried multiple formats and settings and do not see any change in behavior. We are seeing the issue with our implementation as well as with your sample. 

The Mac we are testing on is El Capitan, with Preview application 8.1 (877.7). Please note that the thumbnails on Mac display correctly, the issue only presents itself when the jpg is opened by the Preview application. We have not seen the issue with any other application on Mac or Windows.

I have attached a screenshot of what the image looks like in the Preview application as well as the encoded jpg. The input image used was camera_bt709_422.yuv.

Any guidance you can provide on this issue would be appreciated.

Thanks,
Mike
![mike_test](https://user-images.githubusercontent.com/37155726/46238389-700ca400-c340-11e8-9a76-ed245694e8b4.jpg)
<img width="973" alt="screen shot 2018-09-28 at 4 36 32 pm" src="https://user-images.githubusercontent.com/37155726/46238391-74d15800-c340-11e8-9177-2d824ec526e2.png">

**Comment by MartinPulec** [comment]
Hi Mike,
can you please try to set <code>restart_interval</code> in struct <code>gpujpeg_parameters</code> to zero and look if it helps (or the **-r** parameter in the sample app)?

Thanks,
Martin

**Comment by mkehoe-ovio** [comment]
Hi Martin, 
When I set the restart interval to zero there is still an issue.

**Comment by MartinPulec** [comment]
Hi Mike,
ok, I've tried to reproduce the problem but I was not able to - I used Preview app in El Captain (but version 7.0 (826.4) - don't know why we have different version, the OS should be reasonably updated, except that that is a bit old). However, also in High Sierra, Preview 10.0 (944.5) the image looked ok.

What parameters do you use to encode that sample image? Are able to reproduce it with the command-line application? I've used only a minimal set of parameters to encode the image - <code>gpujpeg -s 1920x1080 -f 4:2:2 -e camera_bt709_422.yuv out.jpg</code>.

Thanks,
Martin

**Comment by mkehoe-ovio** [comment]
It does seem that I have it working correctly with the sample camera_bt709_422.yuv when I set the following: 
param_image.pixel_format = GPUJPEG_422_U8_P1020;
param_image.color_space = GPUJPEG_YCBCR_BT709;
I am working on a windows machine so I am hardcoding the params in the sample application.

I am still able to reproduce the issue when input is rgb in memory. Below is my minimal test case that will reproduce the issue. Please let me know if I am missing something in this code. 

```
struct gpujpeg_encoder_input encoder_input;
struct gpujpeg_parameters param;
struct gpujpeg_image_parameters param_image;
struct gpujpeg_encoder* m_pEncoder = nullptr;

gpujpeg_set_default_parameters(&param);

gpujpeg_image_set_default_parameters(&param_image);

m_pEncoder = gpujpeg_encoder_create(NULL);

uint8_t* image_compressed = nullptr;
int image_compressed_size = 0;

param_image.width = width;
param_image.height = height;
param_image.comp_count = 3;
param_image.color_space = gpujpeg_color_space::GPUJPEG_RGB;
param_image.pixel_format = gpujpeg_pixel_format::GPUJPEG_444_U8_P012;

gpujpeg_encoder_input_set_image(&encoder_input, (uint8_t*)rgbdata);
  
gpujpeg_encoder_encode(m_pEncoder, &param, &param_image, &encoder_input, &image_compressed, &image_compressed_size);

FILE* fOut;
fopen_s(&fOut,"C:/Temp/TestMedia/testImage.jpeg","wb");
fwrite(image_compressed, 1, image_compressed_size, fOut);
fclose(fOut);
```


I also tested this on a Mac with High Sierra, Preview 10.0 (944.5), and was able to reproduce the issue as well.

**Comment by MartinPulec** [comment]
Hi Mike,

unfortunately, I was still not able to reproduce the problem, even with your settings - using 512*512 RGB image (testbars from UltraGrid) GPUJPEG (Linux, GeForce GTX TITAN X) produced image that Previev v10.0 displayed correctly.

So it looks like the issue is not general - would it be possible for you to send me more info about: 1) your platform (OS + CUDA + driver version), 2) graphics card, 3) the RAW image.

Thanks,
Martin

**Comment by MartinPulec** [comment]
Hi Mike,

I am afraid I was still not able to reproduce the error, I've tried encode the image with:
1) Linux, GeForce GTX 1080 Ti, driver 410.57, CUDA 10
2) Windows, GeForce GTX 1060 (Notebook), driver 416.16, CUDA 9.2, VS 2027

(Cannot precisely replicate your settings.) In both cases it has worked. Could you try to reproduce the issue with the command-line application provided in GPUJPEG sources? Windows doesn't have getopt, so please use following patch to hardcode parameters:
        --- a/src/main.c
        +++ b/src/main.c
        @@ -269,7 +269,14 @@ main(int argc, char *argv[])
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;argv += optind;
        &nbsp;#else
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fprintf(stderr, "Parsing command line options isn't implemented in current OS\n");
        -&nbsp;&nbsp;&nbsp;&nbsp;return -1;
        +&nbsp;&nbsp;&nbsp;&nbsp;param_image.color_space = GPUJPEG_RGB;
        +&nbsp;&nbsp;&nbsp;&nbsp;param_image.comp_count = 3;
        +&nbsp;&nbsp;&nbsp;&nbsp;param_image.pixel_format = GPUJPEG_444_U8_P012;
        +&nbsp;&nbsp;&nbsp;&nbsp;param_image.width = 480;
        +&nbsp;&nbsp;&nbsp;&nbsp;param_image.height = 360;
        +&nbsp;&nbsp;&nbsp;&nbsp;encode = 1;
        +&nbsp;&nbsp;&nbsp;&nbsp;argc -= 1;
        +&nbsp;&nbsp;&nbsp;&nbsp;argv += 1;
         &nbsp;#endif
         
         // Show info about image samples range

The application is then called with arguments "*gpujpeg in.rgb out.jpg*".

**Comment by mkehoe-ovio** [comment]
Hi Martin,

Yes we are still seeing the issue when we use the command line application with the patch. 

It appears that Github does not re-encode the jpg when they are uploaded. If you right click on the above rainbow image and save it to your Mac and open it in the Preview application, does it show up correctly? It does not for us on multiple machines.

**Comment by MartinPulec** [comment]
Hi,

that is really weird - provided that the encoded image is really untouched by GitHub, I am still able to display it correctly with Preview 8.1, Preview 10.0 and 10.1 (different Mac machines with 3 different macOS versions) :/ Don't you have an idea what can be different?

Martin

**Comment by mkehoe-ovio** [comment]
Hi Martin,

Not sure what is different. We have verified the issue on 4 different Macs of varying versions and hardware. I have attached another screenshot of the Preview info so maybe you can spot something.

![apple_preview](https://user-images.githubusercontent.com/37155726/46641972-67c71c80-cb29-11e8-995c-9cd6da25078b.png)

**Comment by jstein-ovio** [comment]
Here is another sample of how it looks on one of my Macs.

<img width="1320" alt="screen shot 2018-10-09 at 10 23 59 pm" src="https://user-images.githubusercontent.com/23092061/46714863-6d4c6180-cc12-11e8-9db4-d81b783e2ecf.png">

**Comment by MartinPulec** [comment]
Hmm, similar situation (except of light theme and older HW) here but a different outcome.

![screenshot 2018-10-10 at 17 06 01](https://user-images.githubusercontent.com/9962268/46746402-498b2900-ccaf-11e8-9e92-f8a223a51475.png)

We've got another idea - can you give us an output of `otool -L /Applications/Preview.app/Contents/MacOS/Preview`? Although only a small chance, it is possible the use of different (versions?) of frameworks.

Martin

**Comment by mkehoe-ovio** [comment]
For Preview version 10.0 (944.5):

/Applications/Preview.app/Contents/MacOS/Preview:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.50.160)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 158.0.0)
	/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.0.0)
	/System/Library/PrivateFrameworks/AnnotationKit.framework/Versions/A/AnnotationKit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Quartz.framework/Versions/A/Quartz (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 492.0.0)
	/System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/QTKit.framework/Versions/A/QTKit (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/CorePDF.framework/Versions/A/CorePDF (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis (compatibility version 1.0.0, current version 191.0.0)
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation (compatibility version 1.0.0, current version 2.0.0)
	/System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/SceneKit.framework/Versions/A/SceneKit (compatibility version 1.0.0, current version 433.4.0)
	/usr/lib/libDiagnosticMessagesClient.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (compatibility version 1.0.0, current version 1054.5.3)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.15.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1561.40.100)
	/System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync (compatibility version 1.0.0, current version 4.7.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.15.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1161.8.0)
	/System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage (compatibility version 1.0.1, current version 5.0.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.24.0)
	/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)

**Comment by jstein-ovio** [comment]
Martin, I noticed in your screenshot that you have some sort of NVidia application running.

What is this that you have running? Let me try running the same utility/application and see if that fixes the display issue.

**Comment by MartinPulec** [comment]
Hi Joshua, this is most likely unrelated - it is just safari showing [this](https://gfe.nvidia.com/mac-update) (because macOS 10.14 again broke compatibility of the NVIDIA GPU). Here is another screenshot with different HW (and SW ver):

![screen shot 2018-10-11 at 11 36 03](https://user-images.githubusercontent.com/9962268/46795381-53159f00-cd4a-11e8-814c-2b784cc7f7d3.png)

**Comment by MartinPulec** [comment]
Hi all,

I know it has been a long ago since the last "activity" here and I have to admit that I have no update. But if you want, you can try to change these encoding options:

1. use interleaved JPEG instead of non-interleaved (`gpujpeg_parameters::interleaved`)

2. set `color_space_internal` to _GPUJPEG_RGB_ (you need to checkout newer GPUJPEG version - the older one supported this but wrote JFIF marker which identified the JPEG as YCbCr)

3. use some subsampling (but I'll leave it up to you - it is perhaps not what you want)

I am not sure if anything of the above helps to track down the issue but if some helps perhaps it could work in you workflow?

Martin

**Comment by mkehoe-ovio** [comment]
Hi Martin,

Sorry for the delay on this but I ran into this issue again when importing images into pdfs on acrobat reader and checked out your latest changes. With the latest changes and setting the internal color space, the issue seems to be fixed. 

Appreciate your help with this.
