### ISSUE TITLE
Input sampling factor 4:2:0

### ISSUE THREAD

**Issue by Sanich15** [CESNET/GPUJPEG#2]
I'm working with **YUV 4:2:0** frames that I want to compress to JPEG. 
The supported factors for `param_image.sampling_factor`  are only `GPUJPEG_4_4_4` and `GPUJPEG_4_2_2`.
How is it difficult to add support for 4:2:0 sampling?
The 1st and easy step I did was to modify the `int gpujpeg_image_calculate_size(struct gpujpeg_image_parameters* param)` function. Then, the things start to be a little bit more complicated. So before I go on with this, I wanted to ask if this is something feasible to do or maybe not so much?
If yes, could you please provide some guidelines? Thanks a lot!
Alex Kh.

**Comment by MartinPulec** [comment]
Hi Alex,

provided that you want to compress to JPEG (not decompress), you will 
need to add mainly a loading kernel to gpujpeg_preprocessor.cu in a 
manner similar to 4_4_4 and 4_2_2. As this 2 cases are already handled, 
it is just needed to add the third case in the same way - the kernels 
handle loading and storing to common (comp) format therefore storing 
(and color transformation) would remain mostly the same as in the 
remaining 2 kernels, loading would be different (it also depends which 
format do you use for YUV 4:2:0). Generally speaking, I don't thing it 
will be much difficult, I'd just search through the code for 
GPUJPEG_4_4_4 and where it is used, handle also the new subsampling.


Martin

**Comment by Sanich15** [comment]
@MartinPulec Thank you very much for the quick answer. I'll do it and will update.
By "different format for YUV 4:2:0" do you mean "interlaced/progressive/planar/packed"?

**Comment by MartinPulec** [comment]
Hi,

I meant the layout - planar or packed. You just to make sure you load 
from right place. Currently those 4:2:2 and 4:4:4 formats are packed but 
since you can fetch whichever location you need, there will not be a 
problem with planar I think - if the planes are in memory one after 
another. Only if you have it in different memory locations it will be a 
bit tricky (you will need to pass/transfer to GPU multiple memory block 
etc.).

Martin

**Comment by Sanich15** [comment]
@MartinPulec Now I'm able to work with 4:2:0 planar YUV images. Actually most of the predecessor  (loading kernel) functionality is to decompose the packed format, into 3 color components. As my input image is planar , I already have the components decomposed so what I did is just seting the components pointers of the coder in `int gpujpeg_preprocessor_encode(struct gpujpeg_coder* coder) ` funcion:
```
if (coder->param_image.sampling_factor == GPUJPEG_4_2_0)
	{
		for (int comp = 0; comp < 3; comp++) {
			assert(coder->sampling_factor.horizontal % coder->component[comp].sampling_factor.horizontal == 0);
			assert(coder->sampling_factor.vertical % coder->component[comp].sampling_factor.vertical == 0);

			if (comp == 0) {
				coder->component[comp].d_data = coder->d_data_raw;
			}
			else if (comp == 1) {
				coder->component[comp].d_data = coder->d_data_raw + (image_width * image_height);
			}
			else { // comp=2
				coder->component[comp].d_data = coder->d_data_raw + (image_width * image_height) + ((image_width * image_height) / 4);
			}
		}
	}
```
As mentioned before, I've added a  `GPUJPEG_4_2_0` sampling enum and modified the image size calculation function.
So this issue is closed from my point.
Thanks a lot!
