### ISSUE TITLE
[Error] src/gpujpeg_common.cpp (line 159): Cannot get number of CUDA devices: operation not supported

### ISSUE THREAD

**Issue by PhymurByrd** [CESNET/GPUJPEG#20]
./gpujpeg --decode  ../poster_7088×10630.jpg output.rgb

> [GPUJPEG] [Error] src/gpujpeg_common.cpp (line 159): Cannot get number of CUDA devices: operation not supported.

 nvcc --version

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130

 lspci | grep -i VGA

> 19:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1)
> 1a:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1)
> 67:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1)
> 68:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1)

**Comment by MartinPulec** [comment]
Hi,

can you try to run `nvidia-smi` and paste its contents?

Thanks,
Martin

**Comment by MartinPulec** [comment]
Closed for inactivity
