### ISSUE TITLE
How to reduce encoded jpeg size

### ISSUE THREAD

**Issue by flipbecon** [CESNET/GPUJPEG#21]
Hi，

   i found that by using the same size raw file, GPUJPEG can produce a two times larger file than ffmpeg at the same quality option.

  my input command is
  --encode --verbose --pixel-format=420-u8-p0p1p2 --quality=100 --size=1440x1080 avatar.r avatar.jpg

**Comment by MartinPulec** [comment]
Hi,

would it be possible to provide the encoding command? I've tested that with cjpeg for a sample image from GPUJPEG source:

    gpujpeg -e -s 1920x1080 -f 422-u8-p1020 -q 100 image_bt709_422.yuv out.jpg
    convert -size 1920x1080 -sampling-factor 4:2:2 image_bt709_422.yuv out2.ppm 
    cjpeg -sample 2x1 -q 100 out2.ppm > out2.jpg

It is not exactly the same since "convert" command converts it to RGB. However the size is approximately the same. As for the FFMPEG I am not sure whether it maps the quality exactly to 100 but we can check.

Martin

**Comment by flipbecon** [comment]
hi Martin，

    the ffmpeg command is as follow:
```shell
ffmpeg -f rawvideo -pixel_format rgb24 -video_size 1440x1080 -i avatar.rgb -q:v 1 -qmin 1 -qmax 1 output.jpg
```
    for my personal case, the ffmpeg creates a 331,162 bytes file and gpujpeg creates a 581,271 bytes file.

    sorry to apologize, I checked the created ffmpeg file by using imagemagick, and find out that the quality is 97%. By tuning quality of gpujpeg to 97, it achieved a decent result.

    can you help me check this. 

Best Regards.

**Comment by MartinPulec** [comment]
Hi, okay, thanks for the info. If you have any further regards to that, just reopen the issue.

**Comment by ValZapod** [comment]
Try this, it is even better: https://github.com/mozilla/mozjpeg/issues/182 :)
