### ISSUE TITLE
[GPUJPEG] [Error] src/gpujpeg_common.c (line 361): Device info getting: invalid argument.

### ISSUE THREAD

**Issue by NiclasEsser1** [CESNET/GPUJPEG#26]
I used your library to compress bitmap24 images in a real-time application, so it is possible to send 4k images at 30 fps over TCP to a server. For this, I wrote a JPEG encoder function which uses your API by default. Before image compression, a processing algorithm is executed on the GPU, which is implemented in CUDA. Therefore the GPU is already initialized. When I call the function gpujpeg_init_device(device_id, 0) I get the error message: GPU device is busy. 

So I removed this function call and the image compression now works fine. With the exception that now the error message described in the title appears. Since the images are compressed correctly, I would like to suppress this error message. 

Is it necessary to change the source code of your library on my device? Or can the error message be prevented in some other way?

The source code of the encoder function is shown below:
`
void CudaBase::encodeBmpToJpeg(unsigned char* idata, unsigned char* odata, int* p_jpeg_size, int width, int height)
{
	static int image_num = -1;
	char image_dir[256];
	cudaStream_t stream;
	uint8_t* image = NULL;

	CUDA_CHECK(cudaStreamCreate(&stream));
	image_num++;
	struct gpujpeg_encoder_input encoder_input;
	struct gpujpeg_parameters param;
	struct gpujpeg_image_parameters param_image;
	struct gpujpeg_encoder* encoder = gpujpeg_encoder_create(&stream);

	sprintf(image_dir, "/home/niclas/SoftwareProjekte/Cuda/PerformanceComparsion/results/img/streaming/jpeg/CH%d_%d.jpg", image_num%4, image_num/4);
	gpujpeg_set_default_parameters(&param);
	param.quality = 80;
	param.restart_interval = 16;
	param.interleaved = 1;

	gpujpeg_image_set_default_parameters(&param_image);
	param_image.width = width;
	param_image.height = height;
	param_image.comp_count = 3;
	param_image.color_space = GPUJPEG_RGB;
	param_image.pixel_format = GPUJPEG_444_U8_P012;

	// Use default sampling factors
	gpujpeg_parameters_chroma_subsampling_422(&param);
	if ( encoder == NULL )
		encoder = gpujpeg_encoder_create(&stream);

	gpujpeg_encoder_input_set_image(&encoder_input, idata);
	gpujpeg_encoder_encode(encoder, &param, &param_image, &encoder_input, &image, p_jpeg_size);
	gpujpeg_image_save_to_file(image_dir, image, *p_jpeg_size);

	odata = (unsigned char*) malloc(*p_jpeg_size);
	memcpy(odata, image, *p_jpeg_size);

	CUDA_CHECK(cudaStreamDestroy(stream));
	gpujpeg_image_destroy(image);
	gpujpeg_encoder_destroy(encoder);
}
`

**Comment by MartinPulec** [comment]
Hi,

I am not sure why you are getting the error but can you try to patch the GPUJPEG with following patch:
```
--- a/src/gpujpeg_common.c
+++ b/src/gpujpeg_common.c
@@ -356,7 +356,9 @@ gpujpeg_coder_init(struct gpujpeg_coder * coder)
     // Get info about the device
     struct cudaDeviceProp device_properties;
     int device_idx;
+    gpujpeg_cuda_check_error("before cudaGetDevice", return -1);
     cudaGetDevice(&device_idx);
+    gpujpeg_cuda_check_error("cudaGetDevice", return -1);
     cudaGetDeviceProperties(&device_properties, device_idx);
     gpujpeg_cuda_check_error("Device info getting", return -1);
     coder->cuda_cc_major = device_properties.major;
```

to see which call is actually failing? As you can see, currently it is uncertain if `cudaGetDevice` or `cudaGetDeviceProperties` does (or the error was present before cudaGetDevice call).

Thanks,
Martin

**Comment by MartinPulec** [comment]
As no reply received, I am currently closing. Reopen if more info.
