### ISSUE TITLE
cudaThreadSynchronize is deprecated, suggest changing to cudaDeviceSynchronize

### ISSUE THREAD

**Issue by shi-yan** [CESNET/GPUJPEG#27]
GPUJPEG/src/gpujpeg_huffman_gpu_encoder.cu:976:23: error: 'cudaError_t cudaThreadSynchronize()' is deprecated [-Werror=deprecated-declarations]
     cudaThreadSynchronize();
                       ^
https://stackoverflow.com/questions/13485018/cudastreamsynchronize-vs-cudadevicesynchronize-vs-cudathreadsynchronize

**Comment by MartinPulec** [comment]
Hi, I've pushed that. I think that even cudaStreamSynchronize would be enough, but the init function is not aware of CUDA streams so to be consistent I've followed your suggestion.

Martin

**Comment by MartinPulec** [comment]
Assuming this issue has already been resolved, so closing this for now.
