### ISSUE TITLE
Cannot reproduce the same performance

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#29]
Hi, I am using gpujpeg in order to load images bigger than 4k (6144x3456) but my timing is not create with my 1080 ti : 6144x3456 : 241 msec
I tried a smaller resolution but still not really good : 2160x2160 : 62 msec

I have a feeling I am missing something because your benchmark give much better result. The current jpeg I am using are extracted from a video using OpenCV (using a compression 80).
I am using OpenGL in order to render the frame. All the code is wrapped using SWIG in order to use it from Python, I did some check regarding the overhead here but it really minimal.
The wrapper only take the filename and return the gl texture id. In order to optimize, I generate the param_image just for the first frame and then reuse it for the other frames of the video

Should I do something different regarding how the jpeg is encoded ?

**Comment by MartinPulec** [comment]
Hi Anthony,

first of all it depends whether the JPEG uses restart intervals or not. In case of absence, the Huffman decoder is done on CPU which takes most of the decompress time. You can check it with `gpujpeg -I <image_name>`. If there is one or only a few segments there is a little chance to parallelize the computation. If so but you have the option to set the encoder properties, it would help to let the encoder insert restart markers.

If there is a lot of segments (at least hundreds but better thousands) but it is still slow, there might be a penalty of initialization the CUDA device if doing the decoding for single image. Anyway, if you wish, you can upload the image here and I can check if the performance is reproducible (AFAIK GitHub doesn't reencode JPEGs).


Martin

**Comment by wolfviking0** [comment]
Hi @MartinPulec, I just tested with my frame and here is my result :

./gpujpeg -I frame_0.jpg                                                                                                                                                      
width: 6144
height: 3456
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 1

So I suppose I need to reencode the jpeg with 'gpujpeg' in order to have the segment increased

Tony

**Comment by wolfviking0** [comment]
So here what I did:
```
./gpujpeg --decode frame_0.jpg output.rgb 
./gpujpeg -s 6144x3456 --encode output.rgb frame_0_enc.jpg
```

Now the info are :
./gpujpeg -I frame_0_enc.jpg                                                                                                                                                   
width: 6144
height: 3456
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 82944

Here my result now on OSX with GTX 1080ti (using egpu): 169 msec.

**Comment by wolfviking0** [comment]
FYI @MartinPulec I run my test using a linux machine with RTX 2080 ti.
The 6144x 3456 images take around 16 msec.

Thanks for your help.

Tony

**Comment by MartinPulec** [comment]
Hi Tony,

well, the encoder might be also different than GPUJPEG but the main thing is that it is required to insert JPEG restart markers inside the codestream to create independelty-decodable Huffman code parts. Unfortunately, most encoders doesn't populate the setting, but eg. current FFMPEG's encoder inserts them automatically. 16 ms looks quite OK - not sure of those 169 on mac (is the decode?).

Martin

**Comment by wolfviking0** [comment]
The 169 ms (decoding) on OSX can be explain for few reason, but mainly it the fact I am using an egpu over thunderbolt 2.
But the timing I am able to have on Linux it’s perfect.
Again thanks for you help
Tony
