### ISSUE TITLE
 APP0 marker version should be 1.1 but 1.2 was presented

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#31]
Hi @MartinPulec 

I am trying to generate JPG with ffmpeg and then try to load it using GPUJPEG, but doing that I have this error message.

Do you know more about this issue ?

Thanks

**Comment by MartinPulec** [comment]
Hi Anthony,

yes, a little - the error message means that the decoder expects JFIF 1.01 but the image uses is 1.02 (the error message isn't entirely precise, I'll fix it). This is not critical, the error can removed from the source code.

The problem is that FFMPEG uses only one quantization+Huffman table for both luma and chroma components while GPUJPEG expects more common use of one quantization/Huffman table pair for Y and another for chroma (and only checks if it is so). I forgot about that when I was suggesting encoding with FFMPEG, sorry for that. This would not be hard to fix in code - use the mapping from JPEG generically but no-one had time to do it yet - I'd be glad to do so, but I cannot currently promise it in the nearest future (apart from the check for JFIF version, which I'd perhaps remove if safe).

The good news is that there is a dirty hot fix I've created in [this patch/hack](https://github.com/CESNET/GPUJPEG/files/3907405/patch.gz) (it is against current GIT master, I didn't intentionally remove the error output, however). It is a hack, still - it harcodes the use of single quantization/Huffman table because FFMPEG does it, it is not generic and most encoders use one pair for luma and another for chroma.

**Comment by wolfviking0** [comment]
Hi @MartinPulec,

Thanks for the patch I applied it and was able to check the info of the jpg generated by ffmpeg, unfortunately it seems the ffmpeg do not support GPU:
```
gpujpeg -I 00001.jpg
[GPUJPEG] [Error] APP0 marker version should be 1.1 but 1.2 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
width: 2160
height: 2160
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 1
```

**Comment by MartinPulec** [comment]
Try to add flag `FF_THREAD_SLICE` when encoding, it should be is equivalent to `-thread_type slice` on command line (it is not documented in FFMPEG man page but hopefully should work).

Just FYI, from what I've seen, JFIF 1.02 only adds additional thumbnail formats, so it can be supported directly. The table mapping, however, would still require some work.

**Comment by wolfviking0** [comment]
Hi,

I just test with the command line and the jpg generated has some segment:

```
[GPUJPEG] [Error] APP0 marker version should be 1.1 but 1.2 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
width: 2160
height: 2160
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 136
```

however when I try to decode the jpeg, it failed :

```
Decoding Image [00001.jpg]
Load Image:                1.12 ms
[GPUJPEG] [Error] APP0 marker version should be 1.1 but 1.2 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Error] Decoder can't decode image that has segment count 136 (maximum segment count for specified parameters is 135)!
[GPUJPEG] [Error] Decoder failed when decoding image data!
Failed to decode image [00001.jpg]!
```

**Comment by MartinPulec** [comment]
Interesting, I haven't seen this yet - would it be possible to attach the image (or instructions to create one)?

Thanks,
Martin

**Comment by wolfviking0** [comment]
Here the command I used :
```
ffmpeg -i test_video_4k.mp4 -vf "fps=30" -thread_type slice -q:v 2 frames/%05d.jpg
gpujpeg -I 00001.jpg
gpujpeg -d 00001.jpg 00001.rgb
```

**Comment by MartinPulec** [comment]
Thanks, I checked a JPEG encoded by FFMPEG and it inserts an extra RST marker just at the end of the image. As a quick fix, you can comment out return statement in gpujpeg_reader.c:1018. For me, it looks rather as a bug in FFmpeg for now see ([here](https://www.w3.org/Graphics/JPEG/itu-t81.pdf), figure E.3). I understand it in a way that restart marker should not be inserted when there are is no data left.

**Comment by MartinPulec** [comment]
I've just pushed couple of fixes - i. a. JFIF 1.02 support and suppression of the empty RST marker (which I think is a FFMPEG bug, I'll report if possible). The workaround for table mapping is still required.

FYI, I've just noticed, that you have only 135 segments (FFMPEG emits that), which would mean that GPUJPEG would decode Huffman on CPU (there is a threshold 255 to determine whether it gets decoded on CPU and GPU). AFAIK this is hardcoded in FFMPEG - it inserts restart interval after macroblock row (16 rows). There are two options to avoid - to increase the interval in FFMPEG of change the threshold in GPUJPEG (in `gpujpeg_decoder_decode`). Also if you'd use bigger image, you'd get more segments.

Thanks for testing!
Martin

**Comment by wolfviking0** [comment]
@MartinPulec Thanks for the pull, I will try to give it a try today. BTW using the previous patch you send  me in order to test with ffmpeg, I have some weird artifact when I render the decoded image into my gl textures. Did you have similar artifact ?

**Comment by MartinPulec** [comment]
> using the previous patch you send me in order to test with ffmpeg, I have some weird artifact when I render the decoded image into my gl textures. Did you have similar artifact ?

Well, I didn't tested that thoroughly, only a basic check so I cannot tell. If it persists, would it be possible to attach the JPEG and perhaps also screenshot? (Depends if it would be reproducible or not.)

**Comment by wolfviking0** [comment]
@MartinPulec  Sorry for the delay, I just back working on GPUJPEG.
I will try again with ffmpeg and share with you my result.

**Comment by MartinPulec** [comment]
@wolfviking0  No prob, I've just started to implement the correct solution but as I expected it requires some amount of work, so I cannot provide an ETA now. However, the provided hack is supposed to work - it just overrides the hard-coded tables' mapping with an a priori knowledge of the FFMPEG generated JPEG properties.

**Comment by wolfviking0** [comment]
@MartinPulec I was testing a jpeg saved from preview on OSX and I received this error loading image :
```
gpujpeg -I ~/Desktop/00001.jpg
width: 360
height: 640
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 40
```

```
gpujpeg -d ~/Desktop/00001.jpg ~/Desktop/00001.rgb
CUDA driver version:   10.1
CUDA runtime version:  10.1
Using Device #0:       GeForce GTX 1080 Ti (c.c. 6.1)

Decoding Image [/Users/aliot/Desktop/00001.jpg]
Load Image:                0.87 ms
[GPUJPEG] [Warning] JPEG data contains not supported APP1 marker
[GPUJPEG] [Error] APP13 marker (segment info) scan index should be 0 but 80 was presented!
[GPUJPEG] [Error] Decoder failed when decoding image data!
Failed to decode image [/Users/aliot/Desktop/00001.jpg]!
```

Is it a similar issue of the JPG from ffmpeg ?

**Comment by wolfviking0** [comment]
Hello @MartinPulec 

I run a full pipeline (ffmpeg -> jpeg -> rgb ->jpeg) to test the master branch + your patch you previously give me in order to export jpeg from ffmpeg. 

I attached all the command and result (including images).

### EXPORT JPEG FROM VIDEO WITH FFMPEG
```
ffmpeg -i /Volumes/TRIP\ RAW/GOPRO/GOPR1483.MP4 -vf fps=30 -qmin 1 -q:v 1 -thread_type slice /Volumes/TRIP\ RAW/GOPRO/%05d.jpg
```
### GPUJPEG INFO
```
gpujpeg -I /Volumes/APPLE_MEDIA/WORKSPACE/hugo/data/raw_videos/00001.jpg

[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
width: 1920
height: 1080
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 69
```
### GPUJPEG DECODE
```
gpujpeg -d /Volumes/TRIP\ RAW/GOPRO//00001.jpg /Volumes/TRIP\ RAW/GOPRO//00001.rgb
CUDA driver version:   10.1
CUDA runtime version:  10.1
Using Device #0:       GeForce GTX 1070 (c.c. 6.1)

Decoding Image [/Volumes/TRIP\ RAW/GOPRO//00001.jpg]
Load Image:                1.04 ms
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Error] SOF0 marker component Cb or Cr should have quantization table index 1 but 0 was presented!
[GPUJPEG] [Warning] JPEG scan contains no data after last restart marker!
Decode Image GPU:         24.37 ms (only in-GPU processing)
Decode Image:             37.37 ms
Save Image:               88.85 ms
Decompressed Size:      6220800 bytes [/Volumes/TRIP\ RAW/GOPRO/00001.rgb]
```
### GPUJPEG ENCODE
```
gpujpeg -e -s 1920x1080 /Volumes/TRIP\ RAW/GOPRO/00001.rgb /Volumes/TRIP\ RAW/GOPRO/00001_test.jpg
CUDA driver version:   10.1
CUDA runtime version:  10.1
Using Device #0:       GeForce GTX 1070 (c.c. 6.1)

Encoding Image [/Volumes/TRIP\ RAW/GOPRO/00001.rgb]
Load Image:                4.92 ms
Encode Image GPU:         16.83 ms (only in-GPU processing)
Encode Image:             29.92 ms
Save Image:               36.21 ms
Compressed Size:         475665 bytes [/Volumes/TRIP\ RAW/GOPRO/00001_test.jpg]
```
### GPUJPEG INFO
```
gpujpeg -I /Volumes/TRIP\ RAW/GOPRO/00001_test.jpg
width: 1920
height: 1080
component count: 3
color space: YCbCr BT.601 256 Levels (YCbCr JPEG)
segment count: 12150
```
![00001](https://user-images.githubusercontent.com/2255249/70857706-a6cccc80-1ea8-11ea-9691-8f5ec3752545.jpg)

![00001_test](https://user-images.githubusercontent.com/2255249/70857707-a6cccc80-1ea8-11ea-8025-aa3fce6316c4.jpg)

[00001.rgb.zip](https://github.com/CESNET/GPUJPEG/files/3964571/00001.rgb.zip)

**Comment by MartinPulec** [comment]
Hi @wolfviking0, I am back again.

> Is it a similar issue of the JPG from ffmpeg ?

No, actually it is a misinterpreted marker which could hopefully be ignored. I've pushed a change with such a change. If it won't work, would it be possible to provide the original JPEG?

Thanks, Martin

**Comment by MartinPulec** [comment]
Update 2: I've pushed couple of changes to the [devel](../tree/devel) branch. Most importantly it should add correct support for FFMPEG generated JPEGs. If you find a moment to test it would be superb (but no stress). I'll merge after some testing/check.

**Comment by wolfviking0** [comment]
Thanks, I will be not able to do some test this week but I let you know as soon I am back.

**Comment by wolfviking0** [comment]
@MartinPulec I was able to load frame extracted from ffmpeg with gpujpeg, but it give me a lot of warning:
```
[GPUJPEG] [Warning] Empty segment detected!
```

I also test to load jpg save from osx preview, and it seems to be working fine.
I have one more question, do you know if there is a way to increase the number of segment using ffmpeg from command line ?

**Comment by MartinPulec** [comment]
> @MartinPulec I was able to load frame extracted from ffmpeg with gpujpeg, but it give me a lot of warning:

Does it give you more than one (or few, let say 3 - one for a component) per image?

> 
> ```
> [GPUJPEG] [Warning] Empty segment detected!
> ```
> 
> I also test to load jpg save from osx preview, and it seems to be working fine.
> I have one more question, do you know if there is a way to increase the number of segment using ffmpeg from command line ?

I am afraid there isn't - I've checked the FFMPEG code and it looks like it puts always a restart marker every 8 rows (or 16 for 4:2:0 subsampling).

**Comment by wolfviking0** [comment]
@MartinPulec, I will double check the number of empty segment because I was loading many jpg so I need to test with only one :)

If I decide to build my own version of ffmpeg, where I should patch ffmpeg in order to increase the number of segment ?

Thanks

**Comment by MartinPulec** [comment]
> If I decide to build my own version of ffmpeg, where I should patch ffmpeg in order to increase the number of segment ?
> 
I've checked the code and it doesn't look to be trivial to do so. Not to complicate it much - won't you be able to use a different encoder? Except GPUJPEG and FFMPEG also cjpeg (part of libjpeg) should be able to emit restart markers (and according to the manual page with up to single MCU granularity).

**Comment by MartinPulec** [comment]
Hi @wolfviking0, is there any update on the issue? IIRC from UltraGrid perspective it should be fixed for now. If so, I'd close this issue now (and perhaps reopen another for related ones).

**Comment by wolfviking0** [comment]
Hi @MartinPulec, I am mainly using the dev branch for a while now and no more issue so far.
so I think yes we can closed this one.
Thanks
