### ISSUE TITLE
Different number of segment using gpujpeg_encoder_input_set_gpu_image

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#33]
HI @MartinPulec 

I am currently working with torch tensor (cuda) and I use it with GPUJPEG in order to save the JPEG.

Your API it's seems to be easy to use just calling gpujpeg_encoder_input_set_gpu_image with the gpu memory pointer.

It's worked I think, at least the jpeg look correct but surprisingly the number of segment change:

If I take the tensor bring back to CPU and save it with gpujpeg my number of segment is 10800, if I used GPU tensor directly it's 2700

Also I can see a difference on the size of the file:
CPU Version : 421 KB 
GPU Version : 392 KB

Any idea why this difference, I was suspecting a trouble in my param.quality but It seems to be the same.

Thanks 

Tony

**Comment by wolfviking0** [comment]
Ok It's seems to be related to the default restart interval. What it's the best choise of value for the restart interval ?

**Comment by MartinPulec** [comment]
Hi Anthony,

> Ok It's seems to be related to the default restart interval. What it's the best choise of value for the restart interval ?

yep, that could be one possibility. The best restart interval - it depends what you need to reach. Using bigger (or no reset at all) gains slightly better compression ratio. You can refer to [this article](https://www.researchgate.net/publication/277400442_GPU-accelerated_DXT_and_JPEG_compression_schemes_for_low-latency_network_transmissions_of_HD_2K_and_4K_video), page 10 and 11, comparing compression ratio and compression/decompression times. Usually 8 or 16 are good values for decoder (encoder optimal performance is a bit more biased towards higher values).

Martin
