### ISSUE TITLE
encoder failed on raw file:  format:u8 size:2586x2048

### ISSUE THREAD

**Issue by bmilutin-dh** [CESNET/GPUJPEG#36]
Hi guys, I found a problem with some files. It seems to be related to the width of the file, because the excact same file type with smaller width is working.

Input: 8bit (grayscale) 2586x2048, no padding.
Output jpeg is broken (color is OK, but width calcualtions are wrong).

I also tried the tool gpujpeg.exe that comes with the library, but it's the same result file.
I'm using the latest version from gpujpeg, latest NVIDIA CUDA libs 10.2 on NVidia Geforce 730.

This is the jpeg produced by the library:
![badpixels](https://user-images.githubusercontent.com/62245747/76762906-72f89000-6792-11ea-94b0-cfa792aec91d.jpg)

Here are the raw pixels 
[badpixels.zip](https://github.com/CESNET/GPUJPEG/files/4338404/badpixels.zip)

This is how the image will look correctly (like gimp raw image display)
![correct](https://user-images.githubusercontent.com/62245747/76762875-68d69180-6792-11ea-8b30-5d3e0ab86b3e.jpeg)

Best Regards
Bruno

**Comment by MartinPulec** [comment]
Hi Bruno, thanks for reporting. Your remark is correct – for grayscale images, the widths not divisible by 8 were not handled correctly. This should be fixed now.

Regards,
Martin

**Comment by bmilutin-dh** [comment]
Hi Martin, thank you!!! I tired it again and it is working most of the time. But sometimes I get this message:

[GPUJPEG] [Error] ../GPUJPEG/src/gpujpeg_preprocessor.cu (line 517): Preprocessor copy failed: invalid pitch argument.

Can you have a look at this?

Thanks you
Bruno

**Comment by MartinPulec** [comment]
Sure, my bad, I've forgotten to modify one loop. Could you please try now?

Thanks,
Martin

**Comment by bmilutin-dh** [comment]
Hi Martin, Yes it's working. Thank you for fixing it so quickly!!!! I love that library, it's so fast ;-)

Regards,
Bruno
