### ISSUE TITLE
JPEG data unexpected ended while reading SOS marker!

### ISSUE THREAD

**Issue by locdoan12121997** [CESNET/GPUJPEG#38]
1. Hi Martin, It's me again.

I am using python's ctypes library to import function into python, and I have this error "JPEG data unexpected ended while reading SOS marker!".

My goal is to do the encode and decode operation in c++ while passing the data using python. The data format in Python that I choose to save the image data from c++ is numpy array in python.

I think the encode operation is ok for now because I can see the saved jpg file. However, when passing data from numpy array to the decoder, I encounter this error.

My file
[Python](https://drive.google.com/file/d/1sE1G5MS166F_9T2N8dpQyiR2mmqyxwSC/view?usp=sharing)
[C++ File](https://drive.google.com/file/d/1UpiH3VmH7bdxgOxhQSpGTnneWHNEvdAx/view?usp=sharing)

The command to run the file:
```
nvcc -Xcompiler -fPIC -shared -o libdecode.so decode.cpp -lgpujpeg `pkg-config --cflags --libs opencv`
python test.py
```
[The test image](https://drive.google.com/file/d/1LfrdAYaQxtbKwiQU_cq8w9IC5Solr9tW/view?usp=sharing)

2. I have another question about the performance.
In this [issue](https://github.com/CESNET/GPUJPEG/issues/35), the author use jetson nano to encode and decode image that have size of 2MB with performance around 6ms.
I am using jetson nano to run the [code](https://github.com/CESNET/GPUJPEG/issues/37) to encode and decode 1920x1080 image (raw size 6MB) but get performance around 40-60ms, which is slower than doing the decode in CPU. I have tweak the param.restart_interval with 8 and 16, but still, the speed not improved.
The question is: Is that speed correct for jetson nano platform with my current config?
Thanks.

**Comment by locdoan12121997** [comment]
When the image is encoded in C++, I have check the size of the image, and when I pass back to Python numpy array, I have check the size, and it is the same. This is just a verification of the encoded data.

**Comment by MartinPulec** [comment]
> I am using python's ctypes library to import function into python, and I have this error "JPEG data unexpected ended while reading SOS marker!".

would it be possible to attach the particular JPEG image which is causing this?

> I am using jetson nano to run the code to encode and decode 1920x1080 image (raw size 6MB) but get performance around 40-60ms, which is slower than doing the decode in CPU. 

That is a bit slow but unfortunately I am not sure about the platform. Would it be possible to use the `gpujpeg` testing application and let it encode (decode) and attach the output? Ideally something like:

    gpujpeg -s 1920x1080 -e in.rgb out.jpg --verbose -n 10

The `-n 10` (10x repetition) is important and may partially respond your question – GPUJPEG has an advantage when used for plenty of pictures. For one-timer there may not be a performance gain. Also it is best if encoding/decoding images with same properties (size), not changing them often.

**Comment by locdoan12121997** [comment]
Hi, this is the log for the command `gpujpeg -s 1920x1080 -e in.rgb out.jpg --verbose -n 10`.
[log.txt](https://github.com/CESNET/GPUJPEG/files/4620970/log.txt)

**Comment by MartinPulec** [comment]
I've checked the results and compared to the ones measured by us for NV 580 in [README.md](https://github.com/CESNET/GPUJPEG/blob/master/README.md) and I think that this numbers may be correct.

The model TM660M of Tegra X1 has 236 GFLOPS and 25.6 Gbps memory throughput. NVIDIA GTX 580, which is able to compile at around 7 ms, has 1536 GFLOPS and 192 Gbps throughput. So the encoding time quite matches the performance ratio of the X1 vs the NV580.

**Comment by MartinPulec** [comment]
If there is no further update, I am closing the issue now.
