### ISSUE TITLE
JPEG decode error when using CPU-based huffman decoder

### ISSUE THREAD

**Issue by WANG-lp** [CESNET/GPUJPEG#40]
Hi,
It seems there is a bug in the CPU-based Huffman decoding procedure.
When I decode a JPEG file like this one: [bird](https://data.whicdn.com/images/23195758/original.jpg) ![bird.jpg](https://data.whicdn.com/images/23195758/original.jpg)

 the output `.rgb` file is not correct with CPU-based huffman decoder (without restart markers):
`gpujpeg -f 444-u8-p012 -v -d original.jpg /tmp/test_out.rgb`
![image](https://user-images.githubusercontent.com/1270875/82171642-8fcc5380-98fa-11ea-8734-ba428062d69d.png)

After putting restart markers by jpegtran (`jpegtran -restart 1b original.jpg >original_rst_1b.jpg`)

The decode result becomes correct:
`gpujpeg -f 444-u8-p012 -v -d original_rst_1b.jpg /tmp/test_out.rgb`
![image](https://user-images.githubusercontent.com/1270875/82171833-00737000-98fb-11ea-8ff5-0e3e5d50d61d.png)

I use the following script to show the `.rgb` file in python notebook:
```py
from matplotlib.pyplot import imshow
import os
def read_rgb_444i(fname, width,height):
    with open(fname, 'rb') as f:
        content = f.read()
    assert(width*height*3 <= len(content))
    image = np.zeros(len(content), dtype=np.uint8)
    image = image.reshape((height, width, 3))
    count = 0
    for h in range(height):
        for w in range(width):
            for ch in range(3):
                image[h][w][ch] = content[count]
                count +=1
    return image
img = read_rgb_444i("/tmp/test_out.rgb", 500,335)
imshow(img)
```

Please correct me if I'm wrong.

**Comment by MartinPulec** [comment]
Hi  @WANG-lp ,

thanks a lot for reporting, you are right .It should be caused by the commit 9f04e920. If you wish, you can revert it for now. I'll try to fix it correctly – actually the change should have leaded to more generic handling of the JPEGs.

Regards,
Martin

**Comment by WANG-lp** [comment]
@MartinPulec Thanks for your prompt answer! 
It works with the current master commit, Cheers! 

This issue is closed!
