### ISSUE TITLE
Golang wrapper

### ISSUE THREAD

**Issue by Danile71** [CESNET/GPUJPEG#43]
Hi!)
[src](https://github.com/Danile71/go-gpujpeg)

**Comment by MartinPulec** [comment]
Hi Daniel, thanks, I think that Go users will certainly appreciate that :)

Martin

**Comment by MartinPulec** [comment]
I am thinking about how to incorporate that, 3 ways look viable for me:

1. only referencing it in [README](https://github.com/CESNET/GPUJPEG/blob/master/README.md)
2. adding the code directly to GPUJPEG
3. adding as a submodule

I am mostly thinking about variant 3, which seems best for me - it would be visible to users which can then use that but you will still have an option to update the wrapper in your repo.

**Comment by MartinPulec** [comment]
Ok, I've added it as a submodule in the end in commit fd2368eb. Closing for now.

Thanks,
Martin
