### ISSUE TITLE
Cannot get number of CUDA devices: CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by MI-LA01** [CESNET/GPUJPEG#44]
Hello Guys, 
I compiled inside a container (docker-nvidia) with cuda 10.2. I confirmed the runtime is 10.2 as well as headers residing in the classical placeholder : 
```
lrwxrwxrwx 1 root root 50 Jun 27 05:32 /usr/local/cuda/include -> /usr/local/cuda-10.2/targets/aarch64-linux/include
```
 
I override some build directives because CMake was not able to determine my  CUDA_ARCHITECTURE and preferences for OpenGL  : 
```
cmake -D CMAKE_CUDA_ARCHITECTURES=62 -DOpenGL_GL_PREFERENCE=GLVND ..
```

While trying the freshly built gpujpeg i was surprised to see that : 
```
root@cec5af656a1e:/data/GPUJPEG/build# ./gpujpeg --device-list 
[GPUJPEG] [Error] /data/GPUJPEG/src/gpujpeg_common.c (line 127): Cannot get number of CUDA devices: CUDA driver version is insufficient for CUDA runtime version.
[GPUJPEG] [Error] /data/GPUJPEG/src/gpujpeg_common.c (line 127): 
```

From the container perspective I've enabled the ```--privileged``` flag but not relevant (i guess) for this specific problem. 

I used the master branch for compilation and I already make it works with previous version of GPUJPEG/Cuda(10.0) on the same architecture (TX2). 

Any advices ?

**Comment by MartinPulec** [comment]
Hi Alexis, it looks like there is not a problem with the compiled ultragrid but rather with driver version. Can you check if you meet the required driver version according [this table](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/#cuda-major-component-versions__table-cuda-toolkit-driver-versions)?

Martin

**Comment by MI-LA01** [comment]
Hi Martin, thanks for Your quick answer, actually you are right the underlying cuda driver (host) is 10.0.. meaning this issue is not relevant in this context. thanks anyway.
