### ISSUE TITLE
Mac os x: How to compile in release mode for best performance?

### ISSUE THREAD

**Issue by Sanich15** [CESNET/GPUJPEG#5]
Hi,
I've built the project (with cmake and make ) as a static library, and linked it to my application. 
I see that for 1920x1080 frames and 95% quality, the average encoding time is ~10ms. 
This is a little bit too high. With software (libjpeg-turbo) I'm getting the same (~10ms). 
In addition, I've noticed that drastically reducing the quality to 10% doesn't effect the encoding time (I do see the quality reduction).  I've tried to explicitly set the NDEBUG flag but it didn't help. 
My question is: How to properly compile the project in "release" mode and if you thing I should get a better performance from what I've mentioned.

Thanks!

My setup:
OS X El Capitan (v. 10.11.6)
MacBook Pro (Retina, 15-inch, Mid 2014)
Processor  2.5 GHz Intel Core i7
Memory  16 GB 1600 MHz DDR3
Graphics  NVIDIA GeForce GT 750M 2048 MB

**Comment by MartinPulec** [comment]
Hi,

sorry for late answer - I've been a little bit busy. Well, it actually 
makes sense. It is worth mentioning, that the CPU (Intel i7 4980HQ) is 
nearly high-end processor. While the NVidia 750M is rather a lower 
mid-range GPU (has 750 GFLOPS) while top models of that GPU family had 5 
or 8 TFLOPS. Therefore I am afraid that it is not matter of build flags 
but rather real numbers. GPUJPEG scales linearly with the GPU 
performance, however.

To your second remark - well, it actually makes sense - worse quality 
reduces complexity for decoding but not necessarily for encoding - 
greater part of the compression (copy to device, preprocess, dct) is the 
same, only huffman encoder potentially processes less data (see gpujpeg 
--verbose for details).


Regards,
Martin

**Comment by Sanich15** [comment]
Thanks!
