### ISSUE TITLE
Weird crash with 1 channel texture

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#50]
Hi @MartinPulec, I am facing an issue with GPUJPEG,

I have my own class Image using is own cuda pointer in order to create my pointer I use cudaMalloc and the size of the memory is W * H * C 

When using 1 Channel I have some weird crash coming from GPU JPEG, I feel I am maybe not using the API correctly but here is the function I am using for doing the decoding into my own cuda memory

For 1 channel my option param imagine option are:
        _param_image.pixel_format = GPUJPEG_U8;
        _param_image.color_space = GPUJPEG_RGB;

I add the code I am using but I had a feeling it was a sync problem but after adding the cudaDeviceSynchronize I am still having the issue.

```
bool load(int64_t tensorptr, const std::string& filename)
{
    if (_decoder == nullptr) {
        Log::error("JPGUtil::load(): invalid decoder.\n");
        return false;
    }
    
   cudaSetDevice(_gpu_id);

    gpujpeg_decoder_set_output_format(_decoder, _param_image.color_space, _param_image.pixel_format);

    // load image
    uint8_t* input_image = NULL;
    int input_image_size = 0;
    if (gpujpeg_image_load_from_file(filename.c_str(), &input_image, &input_image_size) != 0) {
        return false;
    }

    // set decoder default output destination
    struct gpujpeg_decoder_output decoder_output;
    gpujpeg_decoder_output_set_custom_cuda(&decoder_output, (uint8_t*)tensorptr);

    if (gpujpeg_decoder_decode(_decoder, input_image, input_image_size, &decoder_output) != 0) {
        return false;
    }
  
    // May be better to syncrhonize
     cudaDeviceSynchronize();

    gpujpeg_image_destroy(input_image);
    return true;
}
```

**Comment by MartinPulec** [comment]
Hi Anthony, is it be possible to create a minimal working example demonstrating the problem where also allocation (and decoder initialization) can be seen? Ideally with main() that could be directly compiled.

Hard to say without the context, but I don't think that explicit synchronization is required unless you are using a different CUDA stream to process the image then (but it is questionable if it is really needed).

Thanks, Martin

**Comment by wolfviking0** [comment]
Hi Martin, 
So it could be tricky to only extract an example, but I just found one more stuff.
In fact I am using GPUJPEG over two gpus and it seems the crash happen using gpu:1
To set the device I am using gpujpeg_init_device inside the constructor.
Is it good enough ?

**Comment by wolfviking0** [comment]
```
#include <cuda_gl_interop.h>
#include <libgpujpeg/gpujpeg_common.h>
#include <libgpujpeg/gpujpeg_decoder.h>
#include <libgpujpeg/gpujpeg_encoder.h>
#include <string>

static const char OUTPUTS[] = "./";

void gpujpeg_test(const uint32_t gpuid, const uint32_t channel, const std::string& filename, bool allocate)
{
    uint8_t* gpuptr;
    if (allocate) {
        cudaSetDevice(gpuid);
        cudaMalloc((void**)&gpuptr, 512 * 512 * channel);
    }

    gpujpeg_init_device(gpuid, 0);
    struct gpujpeg_encoder* encoder = gpujpeg_encoder_create(0);
    struct gpujpeg_decoder* decoder = gpujpeg_decoder_create(0);

    gpujpeg_set_device(gpuid);

    struct gpujpeg_parameters param;
    gpujpeg_set_default_parameters(&param);
    param.quality = 100;
    param.segment_info = 1;
    param.interleaved = 1;

    struct gpujpeg_image_parameters param_image;
    gpujpeg_image_set_default_parameters(&param_image);
    param_image.width = 512;
    param_image.height = 512;
    param_image.comp_count = channel;
    param_image.pixel_format = channel == 3 ? GPUJPEG_444_U8_P012 : GPUJPEG_U8;
    param_image.color_space = GPUJPEG_RGB;

    gpujpeg_decoder_set_output_format(decoder, param_image.color_space, param_image.pixel_format);

    uint8_t* input_image = NULL;
    int input_image_size = 0;
    gpujpeg_image_load_from_file(filename.c_str(), &input_image, &input_image_size);

    struct gpujpeg_decoder_output decoder_output;
    if (allocate)
        gpujpeg_decoder_output_set_custom_cuda(&decoder_output, (uint8_t*)gpuptr);
    else
        gpujpeg_decoder_output_set_default(&decoder_output);

    gpujpeg_decoder_decode(decoder, input_image, input_image_size, &decoder_output);
    gpujpeg_image_destroy(input_image);

    gpujpeg_decoder_destroy(decoder);
    gpujpeg_encoder_destroy(encoder);
    cudaFree(gpuptr);
}

int main()
{
    uint32_t gpu_count = 2 /*CudaUtil::DeviceCount()*/;

    printf("Start RGB Loading Default....\n");
    for (int i = 0; i < 4; i++) {
        uint32_t gpuid = i % gpu_count;
        printf("\tTest %d - Gpu %d\n", i, gpuid);
        gpujpeg_test(gpuid, 3, std::string(OUTPUTS) + "/test_jpg_rgb_save.jpg", false);
    }
    printf(".... End RGB Default\n");

    printf("Start RGB Loading Custom....\n");
    for (int i = 0; i < 4; i++) {
        uint32_t gpuid = i % gpu_count;
        printf("\tTest %d - Gpu %d\n", i, gpuid);
        gpujpeg_test(gpuid, 3, std::string(OUTPUTS) + "/test_jpg_rgb_save.jpg", true);
    }
    printf(".... End RGB Custom\n");

    printf("Start R Loading Default ....\n");
    for (int i = 0; i < 4; i++) {
        uint32_t gpuid = i % gpu_count;
        printf("\tTest %d - Gpu %d\n", i, gpuid);
        gpujpeg_test(gpuid, 1, std::string(OUTPUTS) + "/test_jpg_r_save.jpg", false);
    }
    printf(".... End R Default\n");

    printf("Start R Loading Custom ....\n");
    for (int i = 0; i < 4; i++) {
        uint32_t gpuid = i % gpu_count;
        printf("\tTest %d - Gpu %d\n", i, gpuid);
        gpujpeg_test(gpuid, 1, std::string(OUTPUTS) + "/test_jpg_r_save.jpg", true);
    }
    printf(".... End R Custom\n");
}
```
![test_jpg_rgb_save](https://user-images.githubusercontent.com/2255249/98402491-38db4780-201c-11eb-9da6-10517c8a78ae.jpg)
![test_jpg_r_save](https://user-images.githubusercontent.com/2255249/98402494-3b3da180-201c-11eb-9dce-98487ba639a8.jpg)

**Comment by wolfviking0** [comment]
Hi @MartinPulec  so I spend some time to create this sample using two texture yellow (RGB) and white (R)

Here my understanding of the problem :

1 - If I use gpujpeg_decoder_output_set_default on gpu1 is crash
2 - If I use gpujpeg_decoder_output_set_custom_cuda I have a crash on both GPU using R Texture

Few stuff if I change the size of cuda to W * H * 3 same for R texture it seems to be working better, I think

**Comment by MartinPulec** [comment]
That quite odd, I've tried your code and it works correctly for me (Linux, Ubuntu 18.04, distro CUDA, multiple GTX Titans /1st gen/):
```
Start RGB Loading Default....
        Test 0 - Gpu 0
        Test 1 - Gpu 1
        Test 2 - Gpu 0
        Test 3 - Gpu 1
.... End RGB Default
Start RGB Loading Custom....
        Test 0 - Gpu 0
        Test 1 - Gpu 1
        Test 2 - Gpu 0
        Test 3 - Gpu 1
.... End RGB Custom
Start R Loading Default ....
        Test 0 - Gpu 0
        Test 1 - Gpu 1
        Test 2 - Gpu 0
        Test 3 - Gpu 1
.... End R Default
Start R Loading Custom ....
        Test 0 - Gpu 0
        Test 1 - Gpu 1
        Test 2 - Gpu 0
        Test 3 - Gpu 1
.... End R Custom
```

Not sure if it relevant for the issue but it looks like you are not using current GPUJPEG code - there is missing `cuda_runtime.h` header in your code which prevents compilation (missing declaration of CUDA functions; it was included in former GPUJPEG headers). Although it is possible that in some CUDA version, the header `cuda_gl_interop.h` may include it transitively (anyways, the actual CUDA GL interop header is unneeded in the above code).

**Comment by wolfviking0** [comment]
I was not using the latest master version, I just update everything but I still have the issue.
Inside GPUJPEG I have two patch, 
* I am using gpujpeg as static library
* I update test/decoder_gltex/main.cpp to avoid the build error in OSX (#include <GL/glut.h> must be #include <GLUT/glut.h>)

None of those change explain why I have this issue its really weird.

**Comment by wolfviking0** [comment]
[test_gpujpeg.zip](https://github.com/CESNET/GPUJPEG/files/5512521/test_gpujpeg.zip)
Hi @MartinPulec I made a version of my test starting from scratch with cloning GPUJPEG doing the patch I mention early and building the test, the code build and run fine on OSX using two eGPUs:

the command to use it is :
```
mkdir build && cd build && cmake ../ && make -j 8 && ./gpujpeg_test
```

The error I have :
```
[100%] Linking CXX executable gpujpeg_test
[100%] Built target gpujpeg_test
Start RGB Loading Default....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
	Test 2 - Gpu 0
	Test 3 - Gpu 1
.... End RGB Default
Start RGB Loading Custom....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
	Test 2 - Gpu 0
	Test 3 - Gpu 1
.... End RGB Custom
Start R Loading Default ....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
[GPUJPEG] [Error] /Users/sluser/Desktop/test_gpujpeg/build/gpujpeg-src/src/gpujpeg_decoder.c (line 326): cudaEventRecord((coder->duration_in_gpu).stop, decoder->stream): an illegal memory access was encountered.
[GPUJPEG] [Error] /Users/sluser/Desktop/test_gpujpeg/build/gpujpeg-src/src/gpujpeg_decoder.c (line 333): cudaEventRecord((coder->duration_memory_from).start, decoder->stream): an illegal memory access was encountered.
[GPUJPEG] [Error] /Users/sluser/Desktop/test_gpujpeg/build/gpujpeg-src/src/gpujpeg_decoder.c (line 338): cudaEventRecord((coder->duration_memory_from).stop, decoder->stream): an illegal memory access was encountered.
```

**Comment by wolfviking0** [comment]
Here my result using two linux machine with one and two gpus :
![Screen Shot 2020-11-09 at 10 29 32 AM](https://user-images.githubusercontent.com/2255249/98581563-881cb480-2276-11eb-8157-3ef113d81405.png)

**Comment by wolfviking0** [comment]
Here my result using OSX machine with one and two gpus :
![Screen Shot 2020-11-09 at 10 33 45 AM](https://user-images.githubusercontent.com/2255249/98581967-227cf800-2277-11eb-9adc-73d4cce7e678.png)

**Comment by wolfviking0** [comment]
So the trouble seem to be only when using OSX on GPU 1 with 1 Channel texture

**Comment by MartinPulec** [comment]
Thanks a lot for the instructions! It looks like the problem is that it is not always reproducible, I was perhaps able to reproduce it on an older Mac.

Looks like there is a problem with uninitialized Huffman table for grayscale (or more generally when the JPEG file does't have set first 2 pairs of Huffman tables, which is true for a grayscale). That meant that the occurrence of crash is dependent upon content of garbage memory.

I've pushed a commit a715baba as a first fix that corrected it for me. I could have not, however, tested with multiple GPUs since I don't have such a configuration where I can reproduce that (I guess - Mac). Nevertheless, I guess that it should be that problem - as I mentioned, the occurrence is dependent on circumstances.

If you could test the change it would be perfect.

**Comment by wolfviking0** [comment]
Hi @MartinPulec, so the sample is running fine for me now with two eGPUs, I will integrate the new version in my full code and confirm the fix. But I think it will work.
Thanks for the fix.

```
❯ ./gpujpeg_test
Start RGB Loading Default....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
	Test 2 - Gpu 0
	Test 3 - Gpu 1
.... End RGB Default
Start RGB Loading Custom....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
	Test 2 - Gpu 0
	Test 3 - Gpu 1
.... End RGB Custom
Start R Loading Default ....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
	Test 2 - Gpu 0
	Test 3 - Gpu 1
.... End R Default
Start R Loading Custom ....
	Test 0 - Gpu 0
	Test 1 - Gpu 1
	Test 2 - Gpu 0
	Test 3 - Gpu 1
.... End R Custom
```

**Comment by wolfviking0** [comment]
Thanks @MartinPulec everything seems to be working for me now 👍
