### ISSUE TITLE
Ubuntu 20.04 : stack smashing detected 

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#51]
Hi @MartinPulec,

Running gpujpeg over various configuration I am facing a weird issue with GPUJPEG on ubuntu 20.04.

The call of one of those two functions trigger a crash :
```
        _decoder = gpujpeg_decoder_create(0);
        _encoder = gpujpeg_encoder_create(0);
```

```
*** stack smashing detected ***: terminated
Aborted (core dumped)
```

[EDIT] I rebuild gpujpeg adding those flags :
```
++SET(CMAKE_C_FLAGS "-fPIC -fno-stack-protector")
++SET(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} --compiler-options=-fno-stack-protector")
```
I do not have more crash but I maybe hide the trouble :(

**Comment by MartinPulec** [comment]
Hi @wolfviking0, are there some other steps needed to reproduce the issue? I've tried a simple:
```
#include <libgpujpeg/gpujpeg.h>

int main() {
        auto _encoder = gpujpeg_encoder_create(0);
        auto _decoder = gpujpeg_decoder_create(0);
        gpujpeg_decoder_destroy(_decoder);
        gpujpeg_encoder_destroy(_encoder);
}
```

with Ubuntu 18.04 (default CUDA and GPUJPEG CMake flags) an didn't manage to get the stash smash with GTX TITAN X.

**Comment by wolfviking0** [comment]
Interesting, I will give it another try, the only difference its I am linking gpujpeg statically so maybe here there is something.
Let me try to do a sample to reproduce easily.

**Comment by wolfviking0** [comment]
Hi @MartinPulec I am not able to reproduce this bug with a smaller example. 
Let close it for now I think.

**Comment by MartinPulec** [comment]
Ok, agree - I currently don't have any further idea what could be wrong. It can be reopened anytime.
