### ISSUE TITLE
Performance issue with Ampere GPU 3090

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#55]
Hi @MartinPulec  How are you ?

I am facing a trouble with GPUJPEG on recent GPUs.
I am testing gpujpeg in different configuration but it seems the 3090 its twice slower to encode a frame.

**Ubuntu 18.04 : Cuda Driver 455, Cuda 10.2 Cudnn 8 : 2080 ti**
```
[INFO] 180 4096x4096 frames : encoder_timing 10 msec/frame
[INFO] 180 4096x4096 frames : decoder_timing 1 msec/frame
```
**Ubuntu 20.04 : Cuda Driver 455, Cuda 11.1 Cudnn 8 : 2080 ti**
```
[INFO] 180 4096x4096 frames : encoder_timing 10 msec/frame
[INFO] 180 4096x4096 frames : decoder_timing 1 msec/frame
```
**Ubuntu 20.04 : Cuda Driver 460, Cuda 11.2 Cudnn 8 : 3090**
```
[INFO] 180 4096x4096 frames : encoder_timing 20 msec/frame
[INFO] 180 4096x4096 frames : decoder_timing 2 msec/frame
```

**Comment by MartinPulec** [comment]
Hi @wolfviking0, thanks for the info. I am afraid I don't have any Ampere yet but as soon as I have some access I'll look at it. Until that, would it be possible for you to run the command-line app with `-v` parameter and paste the performance counters? It can be done in other code (see [here](https://github.com/CESNET/GPUJPEG/blob/8d340500592f28d0a2861d429b30d8bcca0757bd/src/main.c#L544-L561)).

**Comment by MartinPulec** [comment]
I'd an opportunity to test on a machine borrowed generously by **Comprimato** with _RTX A6000_  (and Intel i5-4460). Using 7f52770, source was 16x concatenated [colors/camera_bt709_422.yuv](../tree/master/colors/camera_bt709_422.yuv):
```
$ gpujpeg -e -s 7680x4320 -f 422-u8-p1020 -n 1000 -v in.yuv out.jpg
[... omitted ...]
Iteration #1000:
 -Copy To Device:          5.39 ms
 -Preprocessing:           0.39 ms
 -DCT & Quantization:      0.44 ms
 -Huffman Encoder:         0.74 ms
 -Copy From Device:        0.64 ms
 -Stream Formatter:        1.91 ms
Encode Image GPU:          1.58 ms (only in-GPU processing)
Encode Image Bare:         3.49 ms (without copy to/from GPU memory)
Encode Image:              9.53 ms

Avg Encode Duration:       9.70 ms
[... omitted ...]

$ .../NVIDIA_CUDA-11.2_Samples/1_Utilities/bandwidthTest/bandwidthTest
[CUDA Bandwidth Test] - Starting...
Running on...

 Device 0: RTX A6000
 Quick Mode

 Host to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     12.5

 Device to Host Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     12.8

 Device to Device Bandwidth, 1 Device(s)
 PINNED Memory Transfers
   Transfer Size (Bytes)        Bandwidth(GB/s)
   32000000                     642.5

Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.

```

compare to _GeForce RTX 2080 Ti_ (i9-9820X):
```
Iteration #1000:
 -Copy To Device:          5.42 ms
 -Preprocessing:           0.49 ms
 -DCT & Quantization:      0.64 ms
 -Huffman Encoder:         1.20 ms
 -Copy From Device:        0.62 ms
 -Stream Formatter:        1.32 ms
Encode Image GPU:          2.34 ms (only in-GPU processing)                                             
Encode Image Bare:         3.67 ms (without copy to/from GPU memory)                                    
Encode Image:              9.71 ms

Avg Encode Duration:       9.85 ms
```

The results were nearly the same - in-GPU processing was slightly better with the _Amplere_ but not significantly as would performance increase in TFLOPS indicate. I think that this is because the memory bandwidth is now the bottleneck, which is only slightly better for _Amper_. Also PCIe bandwidth is the same.

Assuming your times are including host-to-device transfer? If so, 20 ms is really too much, you could perhaps try the bandwidth test from _CUDA samples_ to see if there is a full bandwidth or not (using perhaps less than 8 PCIe lines or Gen2?).

**Comment by wolfviking0** [comment]
Hi @MartinPulec  thanks to take the time to look at it.

Currently because of the timing do not improve a lot we decide to keep working for now with the 2080 ti.

Thanks

**Comment by MartinPulec** [comment]
Thanks for the info, @wolfviking0, feel free to reopen it if you had new info about this.
