### ISSUE TITLE
About the GPU Memory Leak

### ISSUE THREAD

**Issue by hejinsong** [CESNET/GPUJPEG#57]
Hello,I have met a problem about GPU Memory Leak.
Firstly, I create the encoder and the OpenGL texture like the example, and do the compress method. for now, it work well.
But when I use the method "gpujpeg_encoder_destroy " and the method "gpujpeg_opengl_texture_unregister"  to clear the GPU and the host memory. And I found that the memory used seems increasing slightly.
So I have a try to do this process for several times, to create a encoder, register the OpenGL texture, compress, and destroy them.  I find that the GPU memory is increasing rapidly. and each time about 2Mb .
so I want to know how to avoid that when destroy the encoder? Thanks!

**Comment by MartinPulec** [comment]
Hi @hejinsong, 

thanks for reporting! Would it be possible to provide a minimal working example for that issue?

I've tested it with the included [command-line application](https://github.com/CESNET/GPUJPEG/blob/master/src/main.c) and it doesn't seem to occur for me. (I must have done 2 small fixes to the GL part, but it is already in _master_.) I've simply enclosed [this block](https://github.com/CESNET/GPUJPEG/blob/b40ab2bfbc6a90f1163a3b8548c691ccf42f01d3/src/main.c#L450-L595) with N-time iterated for-loop for the test (and waited on `getchar()` after that). Run with this command:

    dd if=/dev/zero bs=$((1920*1080*3)) count=1 of=black.yuv
    gpujpeg -o -e -s 1920x1080 -f 444-u8-p012 black.yuv out.jpg 

No excessive leaks were observable with _nvidia-smi_ for me. I've also checked RAM memory usage and looked OK as well. Didn't you forget to call `gpujpeg_opengl_texture_destroy()`?

Thanks,
Martin

**Comment by hejinsong** [comment]
Hello @MartinPulec 
I have found the problem is because of the cudaGraphicsUnregisterResource. and it's just occued in the Windows Task Manager.
I just do a test that register the OpenGL texture and unregister the OpenGL. I found the GPU memory is increasing in Task Manage and in the nvidia-smi , it is no excessive leaks . Maybe the cudaGraphicsUnregisterResource method cheated the Windows System?   I'm so sorry about that,  and it seems work well by the nvidia-smi.

**Comment by MartinPulec** [comment]
I see, I've tested only in Linux also because the testing app has context initialization for Linux only. I'll try to take a look at it in Windows.

Instead excessive leak I should have rather used adjective observable - 2 MB per image is quite much. I meant that if the leak were only let say in order of tens of kB, I wouldn't notice. I didn't use cuda-memcheck for that. Anyways, in Linux, there were really no leak observable (after 1000 iterations per 1920x1080 image, the process occupied some ~100 MB of GPU memory).

**Comment by hejinsong** [comment]
I'm agree with you ! thank you very much

**Comment by MartinPulec** [comment]
Hi, I've checked that in Windows and still cannot reproduce your issue, I've run 5000 iterations with following command:

    gpujpeg.exe -o -e -s 512x512 -f 444-u8-p012 ../colors/camera_bt709_422.yuv out.jpg

with [this patch](https://github.com/CESNET/GPUJPEG/files/6148044/main-patch.txt) and measured at the two `getchar()` stops (in patch) GPU memory utilization (invoked from MSYS2, don't bother UNIX-like syntax):

    $ /c/Windows/System32/DriverStore/FileRepository/nv_dispi.inf_amd64_27246fb37cc30d24/nvidia-smi.exe | head -n 10 | tail -n 1
    | 27%   40C    P2    39W / 180W |    292MiB /  8192MiB |      0%      Default |
    $ /c/Windows/System32/DriverStore/FileRepository/nv_dispi.inf_amd64_27246fb37cc30d24/nvidia-smi.exe | head -n 10 | tail -n 1
    | 32%   51C    P2    40W / 180W |    293MiB /  8192MiB |      0%      Default |

which doesn't indicate some significant leak.

Anyways, if you still observe some problem, I'd ask you to provide your code (which you should provide anyways according to [our contributing guidelines](https://github.com/CESNET/GPUJPEG/blob/master/CONTRIBUTING.md#reporting-bugs)).

Thanks,
Martin

**Comment by hejinsong** [comment]
Sorry，I know that it's my fault . because it is just shown in the Windows Task Manager .  and choose the detailed information , select my pocess . in the Register and unregister it may increase. but it actually free the memory by other test tools. sorry that I didn't make it clear

**Comment by MartinPulec** [comment]
Don't worry about that. But I am just now really unsure if you are encountering leaks or not in the end? If so, I'd be grateful for some information (definitely the code, perhaps also screenshots when exactly you are seeing the leaks). Otherwise I cannot help you.

**Comment by MartinPulec** [comment]
I am closing now for inactivity, feel free to reopen with updates.
