### ISSUE TITLE
API to load image for decoding from memory buffer?

### ISSUE THREAD

**Issue by SafrMSD** [CESNET/GPUJPEG#63]
I found an answer for encoding an image 
https://github.com/CESNET/GPUJPEG/issues/28
Is there any solution for decoding images from memory buffer?

**Comment by MartinPulec** [comment]
Sure, if you look at the [prototype of gpujpeg_decoder_decode](https://github.com/CESNET/GPUJPEG/blob/677235b2f2324d0b93b082e8bc42f6594778c74f/libgpujpeg/gpujpeg_decoder.h#L165) then you can see that the input (second parameter) is a pointer to a memory buffer.

**Comment by SafrMSD** [comment]
thank you!
