### ISSUE TITLE
Reinitializing decoder message

### ISSUE THREAD

**Issue by wolfviking0** [CESNET/GPUJPEG#64]
Hi @MartinPulec, How are you ?

I was updating my code to use a more recent version of GPUJPEG and I have now a message in the log coming for each decoding : 
[GPUJPEG] [Info] Reinitializing decoder.

It's seems the code happen only for one set of textures (2048*2048*3). I am loading other resolution but do not have this message.

Its just an info but I have a feeling I am doing something wrong in the code to trigger this message.

**Comment by MartinPulec** [comment]
Hi @wolfviking0,

a little bit context about that - originally GPUJPEG decoder was not able to adapt to different image properties (mainly dimensions) and failed (see the change f1c83c7). This was a bit improved that now it is possible with the above message.

Do you call `gpujpeg_decoder_init()` prior to decoding? It is not needed but if so, if passed different size there than the decoded image props, it should trigger the message. Otherwise it may not occur.

**Comment by wolfviking0** [comment]
Hi @MartinPulec,

So I must have an issue in my code in this case, I am using gpujpeg with a map where the key (width x height x channel x gpuid) point to a decoder.

So in theory the decoder used should always have the correct resolution. Yes I am using the gpujpeg_decoder_init prior to decoding but just one time when creating the decoder.

I will dig into my code maybe something is off.

Thanks

**Comment by MartinPulec** [comment]
Ok, let me know if you find something - it can be also something in GPUJEG. But I've checked the code and the matching check is only looking on _width_, _height_ and component count. But when saying that it is reinitializing, then this is true and there will be some overhead to do so. I usually don't use the preinitialization so not entirely sure.

**Comment by wolfviking0** [comment]
So its seems I need to always use restart interval to 4 otherwise the decoder is reinitialize to use 4. 

Does I miss something in the logic of my code to avoid that ?

**Comment by MartinPulec** [comment]
What is the exact content of `gpujpeg_image_parameters` when calling `gpujpeg_decoder_init()`?

I've checked the situation with the command-line app and it looked correct to me:

    gpujpeg -e -s 1920x1080 -r 12 -f 444-u8-p0p1p2 /dev/zero out.jpg
    gpujpeg -d -s 1920x1080 -r 12 -f 444-u8-p0p1p2 out.jpg out.rgb # <-- reinit does not occur
    gpujpeg -d -s 1920x1080 -r 4 -f 444-u8-p0p1p2 out.jpg out.rgb  # <-- reinit occurs

(The explicit size and pixel format for the decoding is required, otherwise the decoder wouldn't preinit.)

**Comment by wolfviking0** [comment]
Hi @MartinPulec,

I will check one more time but as I mention in my previous message,

the change flag is trigger because of the restart interval, it seems the only parameter different.

Is it the number 4 the default value by any chance ?

**Comment by MartinPulec** [comment]
Hi,

> the change flag is trigger because of the restart interval, it seems the only parameter different.
> 
> Is it the number 4 the default value by any chance ?

The question is where - in `gpujpeg_set_default_parameters()` [it is 8](https://github.com/CESNET/GPUJPEG/blob/677235b2f2324d0b93b082e8bc42f6594778c74f/src/gpujpeg_common.c#L265). But you can of course override it before calling `gpujpeg_decoder_init()`.

**Comment by wolfviking0** [comment]
Is this value part of the texture when saved ?

I look all over the place in my code I never used 4 for the texture when using 2048x2048. But I am using the same logic of adjust_params() in my code.

I keep looking if I found my mistake.

**Comment by MartinPulec** [comment]
> Is this value part of the data texture when saved ?

You mean the compressed JPEG? Yes for sure, the restart interval is a property both of the encoding process and the JPEG itself. On the decoder, the restart interval cannot be changed (well you can change the value for the decoder but it reinitializes according to the JPEG DRI marker contents).

> 
> I look all over the place in my code I never used 4 for the texture when using 2048x2048. But I am using the same logic of adjust_params() in my code.
> 
> I keep looking if I found my mistake.

You can check JPEG file restart interval (content of DRI marker) by issuing:

    $ gpujpeg -I file.jpg
    [...]
    segment count: 12150 (DRI = 8)

(the printout of DRI has just have been added)

**Comment by wolfviking0** [comment]
Hi Martin the texture I was testing was the issue, the 2048x2048 was using DRI 4.

Not sure why, but I will just regenerate the texture to be with a bigger restart interval.

Sorry for that. Mistake was on my hand.

**Comment by MartinPulec** [comment]
No problem, thanks for the info! If it doesn't longer occur we may close the issue?
