### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by redirus** [CESNET/GPUJPEG#8]
When I run tester to test the performance on decoding, something like below showed up: 

Decoding Image [input.jpg]
Load Image:                0.28 ms
[GPUJPEG] [Warning] JPEG data contains not supported APP1 marker
[GPUJPEG] [Warning] JPEG data contains not supported APP2 marker
[GPUJPEG] [Warning] JPEG data contains not supported APP2 marker
Perform huffman decoding on GPU!
Decode Image GPU:          6.36 ms (only in-GPU processing)
Decode Image:             37.80 ms

Decode image time is almost 6x longer than Decode Image GPU.

Why this happened? What does "Decode Image" mean compared to the one with “GPU”?

**Comment by MartinPulec** [comment]
@redirus Hi, to your first question - it depends what those APP markers contain - if the APP1 is Exif metadata, it will likely not work, if those contain just some ancillary data, it is ok, the decoder just ignores them.

Second point - actually no, it is not a comparison. "Decode Image" just tells the complete time while GPU time is obviously only a part of that. If you use '-v' option, gpujpeg gives you few more values to breakdown the complete time. I am not completely sure why the decode time is so high in your case, but as this is a complete time, it may include IO, which may be legitimate justification for the time. I've just tested with sample 1920x1080 image (IO-cached) and the result was something like 2.5 ms complete time and 1.66 ms for GPU processing. However, the reason may be also different - just look at those values with verbose option and it should tell something more. Now I noticed that there is 0.28 for image load, so it should not be a problem, so if you can grab those verbose data it may help (and perhaps also more info about your HW/SW setup).

**Comment by redirus** [comment]
@MartinPulec  Thank you! 
I changed the test jpg file with restart interval. 
And I found that the gpujpeg_decoder_init FUNC took more than 30ms to run for a 2k image. The image size is not filled.
Should I fill the image size first? Will the time consuming decreased?

**Comment by vesor** [comment]
./gpujpeg -v -e -s 1920x1208 -q 90 output.rgb output.jpg
CUDA driver version:   9.1
CUDA runtime version:  9.0
Using Device #0:       GeForce GTX 1070 (c.c. 6.1)

Auto-adjusting restart interval to 8 for better performance.

Encoding Image [output.rgb]
Load Image:                2.33 ms

Allocation Info:
    Segment Count:            13590
    Allocated Data Size:      1920x1208
    Raw Buffer Size:          6.6 MB
    Preprocessor Buffer Size: 6.6 MB
    DCT Buffer Size:          13.3 MB
    Compressed Buffer Size:   26.5 MB
    Huffman Temp buffer Size: 26.5 MB
    Structures Size:          425.0 kB
    Total GPU Memory Size:    80.0 MB

Using faster kernel for preprocessor (precompiled 1x1, 1x1, 1x1).
 -Stream Formatter:  1541056757760.00 ms
Encode Image GPU:          2.20 ms (only in-GPU processing)
Encode Image:             14.23 ms
Save Image:                0.48 ms
Compressed Size:         589613 bytes [output.jpg]

**Comment by Shushon** [comment]
Hello, 

I have question about performance too. I am trying to use the encoder and the results are below. Which settings have to be changed to make it faster? I am using the basic encode example from the readme file.

RGB file which I am trying to encode. -> [Growth_of_cubic_bacteria_25x16_on.zip](https://github.com/CESNET/GPUJPEG/files/2971318/Growth_of_cubic_bacteria_25x16_on.zip)

CUDA driver version:   10.1
CUDA runtime version:  10.0
Using Device #0:       GeForce GTX 1050 Ti (c.c. 6.1)

Encoding Image [Growth_of_cubic_bacteria_25x16_on.rgb]
Load Image:                4.94 ms
Encode Image GPU:         82.50 ms (only in-GPU processing)
Encode Image:            128.86 ms
Save Image:                7.19 ms
Compressed Size:        2653705 bytes [Output_encode.jpeg]

**Comment by MartinPulec** [comment]
Hi,

would it be possible to provides some more details, like encoding parameters? First of all, there is a high difference between "Encode Image GPU" and "Encode Image". Does that mean that you have disabled restart intervals (-r 0) and run Huffman encoding on CPU?

Further - I've just pushed a change that you may encode RGB inside JPEG instead of YUV (-R) which may help a little.

Also, is it possible to process more images at the same time (or for test to use the '-n' parameter)? The result for one image is not really representative since power saving features of the card (unless you set some performance profile).

Regards
Martin

**Comment by Shushon** [comment]
Thank you for your answer, Martin! 

I tried with different settings with no big change for performance. I am using Huffman encoding on GPU. 
Here is my source and the results: -> [Source.zip](https://github.com/CESNET/GPUJPEG/files/2982998/Source.zip)

Regards,

**Comment by MartinPulec** [comment]
Actually there is something strange in your output. Can you send me also command you use? I've tested it on another card (somewhat faster) and get similar Load Image time. However Encode Image GPU was for me 4.54 while you have over 80.

Another interesting thing is that even if I use the quality 100, I get only 3 MB picture, you get 11. Also information about you setup may help. At least you may check if the card has assigned indeed 16 PCIe lines.


Regards,
Martin

**Comment by Shushon** [comment]
Hi,
I don't use command. I hard code the name of the image in to the file. 
SysteInfo -> [SystemInfo.txt](https://github.com/CESNET/GPUJPEG/files/2995607/SystemInfo.txt)
GPU-Info -> ![GPU_Info](https://user-images.githubusercontent.com/47913527/54810583-210c4f80-4c8f-11e9-8c12-0938d69b5278.JPG)

**Comment by MartinPulec** [comment]
Hi again and sorry for a bit delayed response. Didn't you attached a wrong source? I've looked into it and it looks like using the encoder from NVIDIA NPP, not GPUJPEG. On the other hand the output above looked as from GPUJPEG.

Martin

**Comment by MartinPulec** [comment]
Closing for now. If you have some additional info, you can reopen it.
