### ISSUE TITLE
a GPU with multiple threads,  gpujpeg_encoder_encode  error

### ISSUE THREAD

**Issue by wenrunjian** [CESNET/GPUJPEG#85]
If I run a GPU with multiple threads, and each thread is assigned an encode, there will be encode failure :gpujpeg_encoder_encode  error

**Comment by wenrunjian** [comment]
an encode run ok, but Low efficiency

**Comment by MartinPulec** [comment]
Can you provide more info? The code, error message and any relevant details.

Also is it reproducible with [mt_encode.c example](https://github.com/CESNET/GPUJPEG/blob/master/test/misc/mt_encode.c)?

> an encode run ok, but Low efficiency

You mean efficiency in terms of compression ratio or performance? If the second, I'd  also need more details - what is actually the performance you get? You can peek at [measured performance](https://github.com/CESNET/GPUJPEG#encoding) for reference.

**Comment by wenrunjian** [comment]
Thank you very much for your answer. It was a problem with my program

**Comment by MartinPulec** [comment]
> Thank you very much for your answer. It was a problem with my program

Ok, thanks for the info. I am not sure if you also resolved the efficiency problem so I keep it open for a while. You can look into [FAQ](https://github.com/CESNET/GPUJPEG/blob/master/FAQ.md) for common problems - generally speaking to achieve a good performance it is needed to:

1. encode a large amount of pictures with the encoder - CUDA initialization is costly, encode of first picture can last as much as 100 times the time of the subsequent ones. Ideal is if picture properties don't change (much) while encoding different picture (it is optimized to process a huge amount of same images)
2. use restart intervals – `gpujpeg_parameters::restart_interval` is set to _8_ by `gpujpeg_set_default_parameters()`, which is more or less ok. If you'd set it to zero, also by not calling  _set_default_parameters_ but [empty-initialize](https://en.cppreference.com/w/c/language/initialization#Empty_initialization) (or [zero-initialize](https://en.cppreference.com/w/cpp/language/zero_initialization) in C++) structure instead, it will use CPU encoder for Huffman coding, which is slow (also described in the FAQ, 2. question).
