### ISSUE TITLE
How to use multi-GPU parallelism

### ISSUE THREAD

**Issue by wenrunjian** [CESNET/GPUJPEG#86]
We can't seem to set the GPU number, and we do, it doesn't work
 if (gpujpeg_init_device(2, 0)) //  doesn't work

how to use

thanks!!

**Comment by MartinPulec** [comment]
Please provide the code, without that it is hard to talk about. For instance:

>  if (gpujpeg_init_device(2, 0)) // doesn't work

I don't know exactly what you mean that it doesn't work - `gpujpeg_init_device` returns 0 on success, so you mean that it doesn't succeed (so in your case the if-branch is entered)? If this is the case, the function prints the error message in case of any error, what does it print to you?

**Comment by wenrunjian** [comment]
Thank you very much for your answer. The problem has been solved

**Comment by MartinPulec** [comment]
> The problem has been solved

Thanks for the info, so I am closing it now.
